### ISSUE TITLE
Plugin does't work statamic V1.11.0 

### ISSUE THREAD

**Issue by serieseight** [lesaff/statamic-vanity#1]
Hey I installed this and for some reason I get a error message 

"That page did not exist, so we sent you here instead." which is the standard CP homepage any Ideas I have got my vanity file in the _config file and everything is setup it just wont load.

Cheers,
Mario

**Comment by lesaff** [comment]
Did you add `vanity:    true` in your `settings.yaml` or environments setting (if you use them)?

**Comment by serieseight** [comment]
figured out the folder should be called vanity and not statamic-vanity :)

**Comment by lesaff** [comment]
:+1: , let me know if I need to adjust the readme to make that clearer. By the way, this addon will be available natively in V2.

**Comment by serieseight** [comment]
Its awesome @lesaff :)
